### PR TITLE
move mongoose to peerDependencies

### PR DESCRIPTION
**Pull request by bobzoller**
move mongoose to peerDependencies and lock it to 4.x

### CODE REVIEW

**Comment by bobzoller** [comment]
!version 1.9

**Comment by goodeggs-mk** [comment]
@bobzoller: usage: !version &lt;major,minor,patch&gt;

Mimics running `npm version && git push --follow-tags` on the master branch.

**Comment by bobzoller** [comment]
!version minor

**Comment by goodeggs-mk** [comment]
@bobzoller: pushed new version 1.9.0 to master in 98c3ba8196515eb6c20371404e1a75178ce11cb3.

**Pull request merged**
